# deamon manager
exec-once=hypridle

#night light
exec-once= hyprsunset


# status bar
exec-once=waybar

# notification daemon
exec-once=dunst

# network manager 
exec-once=nm-applet --indicator & disown

#background
# exec-once=swaybg --image ~/Documents/sfondi/black-rose_dragon.jpg --mode fill
# exec-once=swaybg --image ~/Documents/sfondi/black-rose_dragon.jpg --mode center
exec-once=swaybg --image ~/Documents/sfondi/threekings.jpg --mode fill
# exec-once=swaybg --image ~/Documents/sfondi/threekings.jpg --mode fit

# audio equalizer
exec-once=easyeffects --hide-window --gapplication-service --load-preset Laptop

# power management from KDE Plasma - REMEMBER to disable "inactivity" sleep on plasma power settings...
# to show power stats: kinfocenter kcm_energyinfo
exec-once=systemctl --user start plasma-powerdevil

#player
exec-once = playerctl

#workspaces
exec-once = [workspace 1 silent] kitty -e tmux 
exec-once = [workspace 10 silent] kitty --working-directory ~/Documents/libri/ -e sioyek 22.pdf
exec-once = [workspace 2 silent] kitty --working-directory ~/Documents/appunti/
exec-once = [workspace 3 silent] librewolf
exec-once = [workspace 4 silent] kitty --working-directory ~/.config/nvim/lua/

