# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,highres,auto,1
env = XCURSOR_SIZE,20
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = workspace 4 silent match:class gimp
windowrule = workspace 6 silent match:class ZapZap
windowrule = workspace 7 silent match:class org.telegram.desktop
windowrule = workspace 8 silent match:class vesktop
windowrule = workspace 9 silent match:class Spotify
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER
