# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,highres,auto,1
env = XCURSOR_SIZE,20
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = workspace 4, match:class gimp
windowrule = workspace 6, match:class ZapZap
windowrule = workspace 7, match:class org.telegram.desktop
windowrule = workspace 8, match:class vesktop
windowrule = workspace 9, match:class Spotify
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER
