# See https://wiki.hyprland.org/Configuring/Monitors/
monitor =,highres,auto,1
env = XCURSOR_SIZE,20
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = workspace 2, match:class sioyek
windowrule = workspace 5, match:class gimp
windowrule = workspace 7, match:class ZapZap
windowrule = workspace 8, match:class org.telegram.desktop
windowrule = workspace 9, match:class vesktop
windowrule = workspace 10, match:class Spotify
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER
env = HYPRSHOT_DIR,~/Desktop/Screenshots/
